### ISSUE TITLE
Launch App using KeyCode?

### ISSUE THREAD

**Issue by mikebronner** [tekezo/Karabiner#204]
Is there a way to launch an app using a key code?

**Comment by cprovatas** [comment]
@mikebronner Link not working, do you remember how you solved?

**Comment by alexrsmith16** [comment]
@cprovatas Here you go
https://pqrs.org/osx/karabiner/json.html#typical-complex_modifications-examples
Look for Open Alfred 3 if escape is held down. I needed o add some description stuff at the beginning in order to get to show up in karabiner. I would also recommend changing it to control then some key or command and some key.
