### ISSUE TITLE
Smooth Mouse + Karabiner

### ISSUE THREAD

**Issue by aristidesfl** [tekezo/Karabiner#374]
Any chance it might be possible to make a kext which combines Smooth Mouse with Karabiner pointing devices?

**Comment by tekezo** [comment]
Smooth Mouse and Karabiner grabs same kernel function and it's difficult to coexistence together at the moment.

**Comment by aristidesfl** [comment]
Impossible though?

**Comment by tekezo** [comment]
Smooth Mouse and Karabiner modify a function pointer (_relativePointerEventAction) in order to inject own function.
The problem will be happen when unloading kext, they restore original _relativePointerEventAction value when unloading, but saved value may refer another kext that is already unloaded.

We need to define a shared protocol of grabbing kernel function with Smooth Mouse and Karabiner.
For example, making KernelMonkeyPatchKit that replaces kernel function pointer by managed way and use that in both projects.

**Comment by clarkewd** [comment]
I would love to see these two apps working together. I had Karabiner running, then installed SmoothMouse and everything was great. But after restarting I noticed that Karabiner was no longer working and got the message

> A conflicting application is installed: Smooth Mouse

Unfortunately I had to uninstall SmoothMouse because it is less crucial for me than Karabiner - but I would really like to have both. I donated to both projects, the PayPal receipt for SmoothMouse was `cacyberic@cyberic.eu` so perhaps we can contact them and ask about something like the suggested `KernelMonkeyPatchKit` pointer.

**Comment by sashton-stoneware** [comment]
+1 for this feature. Would be nice if it's possible

**Comment by undeadlegion** [comment]
@clarkewd did you ever get in contact with them? I'm sure there are others who want to remap their keyboard as well as disable mouse accel

**Comment by clarkewd** [comment]
never heard back from them

**Comment by aristidesfl** [comment]
I wonder if the would be technically possible to restrict Karabiner to the trackpad and SmoothMouse to USB mice. That would require less coupling between the projects and satisfy many use cases.

**Comment by mmoole** [comment]
Well, I am also in a dilemma here:
I would like to map the 4th and 5th button of the mouse to Mission Control, but also use a usable mouse pointer acceleration like on Linux/Windows.
So if on their side nothing happened, why not try to make mouse pointer acceleration an option that could be set to native, none and linux like?

greetings

**Comment by aristidesfl** [comment]
Basically integrating SmoothMouse into Karabiner?

**Comment by mmoole** [comment]
Well, I dont specially propose to include SmoothMouse into Karabiner, but I think there are lots of small bits of a few other apps, be it on mac, linux or windows, that are free and open source and that could serve as some points for inspiration for mouse pointer movement settings. 
The most basic thing would simply be to offer two new options:
* set mouse acceleration to a specific scheme 
* and provide a slider or a number to adjust this scheme.
But it seems that the problem to solve isn't really about what acceleration algorithm to use but about how to get it to work on current El Capitan?

**Comment by nkgm** [comment]
+1 @mmoole. I would think there's already a big overlap between the two: plumbing, preference panes, updaters etc. Most of the essence appears to be [here](https://github.com/capitalfuse/SmoothMouse/blob/master/SmoothMouseDaemon/mouse.mm) and [here](https://github.com/capitalfuse/SmoothMouse/tree/master/SmoothMouseDaemon/libpointing).

    But it seems that the problem to solve isn't really about what acceleration algorithm to use but about how to get it to work on current El Capitan?

AFAIK Karabiner is already doing the plumbing required for this. Why would El Capitan be a problem?
