### ISSUE TITLE
Change menu bar color at ShowStatusMessage

### ISSUE THREAD

**Issue by tekezo** [tekezo/Karabiner#44]
Change menu bar color like DrasticInputSourceStatus.
http://pqrs.org/macosx/DrasticInputSourceStatus/index.html

**Comment by Januzz** [comment]
In my opinion, it would be really great if one could instead of the current implementation which overlays a thin (depending on selected font size) red bar over the menu bar have the whole menu bar colored like this tool does: http://apple.stackexchange.com/questions/46413/change-mac-menu-bar-color

I would further like to option to have both the menu bar coloring (which is in my opinion the most obvious option) and the bezel, because the menu bar option does not enable one to see, e.g., which mode vim-emu is in etc.

Thanks!

**Comment by tekezo** [comment]
@Januzz 
I've adjusted the height at v10.7.12.
Please upgrade Karabiner to the latest beta version and try "Font size: Huge". 

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by Januzz** [comment]
Great, thanks!
