### ISSUE TITLE
Version 10.9.0 Regression

### ISSUE THREAD

**Issue by mwean** [tekezo/Karabiner#475]
I just updated to 10.9.0 and started to experience some weird behavior. I tried the 10.9.4 beta (which had the same problem) and reverted back to 10.8.0 (which fixed it). My setup:

- Caps lock remapped to option through keyboard preferences (not Karabiner)
- Diamond cursor remapping (Option_L+IKJL to Up/Down/Left/Right)
- Custom mapping for right command to control:
```
<item>
    <name>Command_R to Control_L</name>
    <identifier>remap.commandR2controlL</identifier>
    <autogen>--KeyToKey-- KeyCode::COMMAND_R, KeyCode::CONTROL_L</autogen>
</item>
```

The issue I'm seeing is that if I use `caps lock` + `option` + `J/K/L/I` to move between words, then release the option key (while still holding `caps lock`) and hit `J/K/L/I` it types the letters instead of moving the cursor. If I release `caps lock` and hold it again, it works fine.

Is there a change that I need to make to prevent this in the new version, or is it a bug?

**Comment by tekezo** [comment]
Sorry for inconvenience.

If the same key in the same keyboard exists, Karabiner unites them since v10.9.0.
So, the key will be treated as released when either one key is released.

I'll add an option for this case.
Use v10.8.0 until it.

Or avoid the same key in the same keyboard by following procedure.
1. Change caps lock to PC Application key (keycode 110) by Seil.
2. Then, change the key by Karabiner (Application Key to Option_L).

**Comment by mwean** [comment]
I'll give that a try, thanks!

**Comment by tekezo** [comment]
I've added this option for keyboard that has multiple same key at Karabiner v10.9.6.
Please upgrade Karabiner to the latest beta version and use this option together.

<img width="652" alt="screen shot 2015-09-12 at 9 52 33 pm" src="https://cloud.githubusercontent.com/assets/659178/9831597/2852e3a4-5999-11e5-9b03-1d958718e164.png">

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by mwean** [comment]
That works, thanks!
