### ISSUE TITLE
"Karabiner cannot connect with kernel extension"

### ISSUE THREAD

**Issue by JoshuaC3** [tekezo/Karabiner#490]
I have the most recent verson of karabiner but unfortunately this is not working for me. What other information do you need from me in order to help me out?

**Comment by tekezo** [comment]
The message might be shown when multiple users are using your Mac.
At first, please restart your Mac.

**Comment by JoshuaC3** [comment]
I re-read some of your other troubleshooting/bug reports and have solved my problem. It was not the multiple user, as I have no other users; it was my external keyboard. I kept restarting my Mac and needed the external keyboard attached to log in so never unplugged it. Unplugged after start up and now works.
Many thanks and thank your such a great program.

**Comment by tekezo** [comment]
Your issue seems like this issue.
https://github.com/tekezo/Karabiner/issues/211

Did you install Microsoft IntelliType?

**Comment by JoshuaC3** [comment]
I didn't install this myself. It is an external USB keyboard, specifically a Mac one. So I don't know if this something that auto-installs.

**Comment by tekezo** [comment]
Thank you for reply. I see.
If this issue is reproduce in each reboot, please show me Console logs.
https://pqrs.org/osx/karabiner/faq.html.en#console

**Comment by kopepasah** [comment]
I am getting this same notification while setting up on my new computer (El Capitan) and wonder if it is related to the System Integrity Protection setting.

I am not using Microsoft IntelliType.

Any help would be appreciated.

**Comment by tekezo** [comment]
@kopepasah 

Karabiner works well with the System Integrity Protection.

If you are running OS X in safe mode (shift key is pressed at boot), you have to switch to normal boot.
See this article.
https://pqrs.org/osx/karabiner/faq.html.en#shift

Otherwise, please restart your system once.
If your issue is reproduce after reboot once, please show me Console logs.
https://pqrs.org/osx/karabiner/faq.html.en#console

**Comment by kopepasah** [comment]
@tekezo 

Thanks for the response and I tried what you mentioned; however, I am still unable get the application working on my new machine.

Here is my log: https://gist.github.com/kopepasah/01c43eac1037260d2286

In addition, after a few moments the following notification appears: http://juko.d.pr/kE3A

Thanks in advance for your assistance.

**Comment by tekezo** [comment]
@kopepasah 

Thank you for information.
I think you failed to load the kext of Karabiner.

Could you execute this command in Terminal and show me result?
(This command requires administrator privilege.)

```shell
sudo kextload '/Library/Application Support/org.pqrs/Karabiner/Karabiner.signed.kext'
```

**Comment by kopepasah** [comment]
@tekezo here is the output.

```/Library/Application Support/org.pqrs/Karabiner/Karabiner.signed.kext failed to load - (libkern/kext) not found; check the system/kernel logs for errors or try kextutil(8).```

**Comment by tekezo** [comment]
@kopepasah 
Thank you for confirmation.
Some Karabiner files have been removed for some reason on your system.
Please reinstall Karabiner from package.
https://pqrs.org/osx/karabiner/

**Comment by kopepasah** [comment]
@tekezo that worked. Thanks for the help.

I should have tried that first. Sorry for the inconvenience.

**Comment by hueyhedji** [comment]
@tekezo 
I encounter the same problem. Here is the log:


16/8/19 上午10:25:41.720 SubmitDiagInfo[803]: Couldn't load config file from on-disk location. Falling back to default location. Reason: Won't serialize in _readDictionaryFromJSONData due to nil object
16/8/19 上午10:25:41.722 SubmitDiagInfo[803]: Couldn't load config file from on-disk location. Falling back to default location. Reason: Won't serialize in _readDictionaryFromJSONData due to nil object
16/8/19 上午10:25:42.808 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:42.808 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:42.808 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:42.808 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:42.808 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:42.808 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:42.808 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:42.808 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:42.808 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:42.809 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:42.809 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:42.834 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:42.842 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:42.865 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:47.428 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:56.965 Console[821]: Failed to connect (_consoleX) outlet from (NSApplication) to (ConsoleX): missing setter or instance variable
16/8/19 上午10:25:57.852 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:58.066 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
16/8/19 上午10:25:58.113 Karabiner[715]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null

**Comment by kopepasah** [comment]
@hueyhedji did you try @tekezo's [suggestion above|https://github.com/tekezo/Karabiner/issues/490#issuecomment-191595595]?

**Comment by hueyhedji** [comment]
@kopepasah Yes I have tried, but still does not work

**Comment by hueyhedji** [comment]
@kopepasah Though I got the same out put as you did after executing ```sudo kextload '/Library/Application Support/org.pqrs/Karabiner/Karabiner.signed.kext'``` this command. 
It seems that some karabiner files still missing after the reinstall.

**Comment by RafaelCosman** [comment]
When I run `sudo kextload '/Library/Application Support/org.pqrs/Karabiner/Karabiner.signed.kext'`

I get

`/Library/Application Support/org.pqrs/Karabiner/Karabiner.signed.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).`

**Comment by RafaelCosman** [comment]
Problem solved -- I had to go into recovery mode and run `csrutil disable`.

**Comment by tekezo** [comment]
Generally you don't need to disable System Integrity Protection to use Karabiner.
(And you should not disable SIP for security reason.)

However, if you are using self build Karabiner (not signed with Developer ID),
you have to exclude kext from SIP to load your kext.
`csrutil enable --without kext`
