### ISSUE TITLE
Key repeat is noticeably delayed

### ISSUE THREAD

**Issue by Aethon** [tekezo/Karabiner#505]
Yosemite 10.10.1
Karabiner 10.13.0

After installing, the delay before key repeat starts is noticeably (painfully) longer than the system default, even "Overwrite the key repeat values of system" is not checked.

**Comment by tekezo** [comment]
Karabiner reflects the system key repeat rate since v10.13.0.
Please adjust the values in System Preferences > Keyboard.
https://pqrs.org/osx/karabiner/document.html.en#keyrepeat

The previous version of Karabiner uses the following values as default.

* delay until repeat: 500ms
* key repeat: 83ms

If you want the previous speed, adjust to "416 and 33".
Or specify "500 and 83" with "Overwrite the key repeat values of system" setting.

**Comment by dmytro-shchurov** [comment]
+1 Since 10.14.0 on El Capitan 10.11.1

**Comment by DominoTree** [comment]
Just installed 10.20 on a fresh install of El Capitan 10.11.5 and it changed my existing system settings to delay until repeat: 1133ms, key repeat: 100ms.

This has happened before but I didn't report it because I wasn't sure what was doing it.  I specifically watched for it this time, and it happened after installing and running Karabiner.  Was an easy fix, but unexpected.

**Comment by tekezo** [comment]
@DominoTree Thank you for feedback!
I've confirmed this issue and fixed it at Karabiner-10.21.0.

**Comment by hanns** [comment]
Notice similar issue on Sierra, anyone else experiencing same?

**Comment by javadba** [comment]
Key repeat delay is not working on El Capitan:  remains very slow.  No setting value that I put makes any diffference.   I have 10.22

**Comment by nikisix** [comment]
i'm seeing this on:
karabiner: 10.22.0
osx-sierra: 10.12.3
