### ISSUE TITLE
"`" and "§" swap for 2 languages

### ISSUE THREAD

**Issue by NekR** [tekezo/Karabiner#512]
I use 2 languages on Russian and English and want to swap those buttons for both. It works if a swap them only for Russian or for English, but when I swap for both langs, only English gets swap.

![image](https://cloud.githubusercontent.com/assets/1189265/11096473/f14c229c-88a2-11e5-9e38-a14cff21437d.png)

I use Russian-PC layout and saw this issue: https://github.com/tekezo/Karabiner/issues/180 but it works for Russian-PC layout actually, problem is that it does not work in conjunction with swap for English lang.

**Comment by tekezo** [comment]
The prepared "Swap the Tilde..." setting does not check the current input source.
Therefore, the setting swaps two keys in the both input source.

Please use this new setting instead of the prepared setting.
https://github.com/tekezo/Files/blob/master/Karabiner/private.iso_swap_tilda_section/private.xml

**Comment by NekR** [comment]
@tekezo wow, works great now, many thanks!
