### ISSUE TITLE
Brightness controls with multi monitor setup

### ISSUE THREAD

**Issue by simar7** [tekezo/Karabiner#523]
Hello,

Thanks for making Karabiner awesome! I just ran into a small issue while I was trying to configure my setup. I noticed that when I select the F1/F2 to change brightness levels, they map to the brightness levels on my main monitor (Macbook) and not my extended monitor (iMac display).

Is this an issue? If not what options can I use to map the keys to change brightness levels on my extended display instead?

**Comment by tekezo** [comment]
I believe it's an issue of OS X.
There are some key codes to control brightness but they do not work well either  internal or external monitors.

This version of brightness controls might work well on your environment.
Please try new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.f1_to_iohidpostevent_brightness_down/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by simar7** [comment]
hey @tekezo thanks for getting back! Unfortunately, these settings did not work :disappointed: Is there anything else I can try? Also where can I look for other OS X key codes that might work?

**Comment by tekezo** [comment]
I updated private.xml.
https://github.com/tekezo/Files/blob/master/Karabiner/private.f1_to_iohidpostevent_brightness_down/private.xml

These three versions are all of brightness controls.
(You cannot use these settings together. Please enable either setting.)

The second setting might change your extended display but it might not change internal display.

**Comment by simar7** [comment]
Thank you trying again @tekezo unfortunately, they also didn't work :sob: But thank you for being so responsive on GitHub!

**Comment by tufu9441** [comment]
I have tried your latest private.xml using an external PC keyboard and an external monitor: when I chose the first or the third setting or none of them with the Macbook monitor open, the F1 and F2 buttons of the PC keyboard can control the brightness of the Macbook monitor rather than the external one, even though the control bar also appeared on the external monitor; when I chose the second setting, the F1 and F2 buttons of the PC keyboard did not work on both monitors. 

When I closed the Macbook display, the F1 and F2 buttons of the PC keyboard were not able to control the brightness of the external monitor, and the control bar also did not show, no matter which setting I chose. FYI.
