### ISSUE TITLE
(Swap numbers and symbols) + (CapsLock+1234567890 to !@#$%^&*())

### ISSUE THREAD

**Issue by jtreminio** [tekezo/Karabiner#535]
Love your work.

This used to work in keyremap4macbook.

Have the following enabled:

![image](https://cloud.githubusercontent.com/assets/589398/11871607/5495b5a2-a496-11e5-8b6e-d2d1146caff0.png)

Without caps, works as intended, can get numbers with shift held down.

With caps, has no effect. Caps used to override the first setting, basically switching the number row back to original while caps was activated. Now, nothing happens.

Is this a bug or a feature? Any way to get around it?

**Comment by tekezo** [comment]
For your purpose, please use new setting instead of prepared settings.
You can add new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.swap_number_and_symbol_unless_caps/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by jtreminio** [comment]
@tekezo that's perfect, thank you so much.
