### ISSUE TITLE
Auto Copy on Select

### ISSUE THREAD

**Issue by typkrft** [tekezo/Karabiner#557]
I would like to be able to select "some text" then on the release of the left mouse button trigger command+c. I can get the Left click to copy, but when I do I am no longer able to select any text. No sure if it's possible, but I figured this would be the best place to ask. Thanks!

**Comment by tekezo** [comment]
Karabiner can not detect whether you selected text or not.

Therefore, Karabiner always sends command+c for each releasing of the left button to achieve auto copy. (You can do it by the following autogen.)

But this setting forbits double click.
You should consider to use another trigger.

```xml
    <autogen>
      __KeyToKey__
      PointingButton::LEFT,
      PointingButton::LEFT,

      Option::KEYTOKEY_AFTER_KEYUP,
      KeyCode::C, ModifierFlag::COMMAND_L,
    </autogen>
```

**Comment by typkrft** [comment]
Would it be possible to, after dragging while still holding the left click to click the space bar and have that perform the copy function? Would a long click to copy or a delay before copying help? Again I totally appreciate this. It is as close as I've come to getting that functionality.

For anyone who comes across this looking for the same thing. Here's a little background. 
I tried to create an automator service to copy selected, but it doesn't work in every app. Then I tried to edit your code a bit to run shell call to command+c in applescript, still can't double click. Then I started using your <not> tag to filter out apps. Maybe it is not meant to be, haha! Maybe someday Ill learn objc, pop clip is so close too, but you can't programmatically check to see if pop clip bubble is up, but you can control the bubble with applescript.

**Comment by tekezo** [comment]
> Would it be possible to, after dragging while still holding the left click to click the space bar and have that perform the copy function?

I think you should work to get the selection text instead of tuning the command+c timing.

You might be able to get the selection text by Accessibility APIs.
http://stackoverflow.com/questions/6544311/how-to-get-global-screen-coordinates-of-currently-selected-text-via-accessibilit

Then, make shell command which sends command+c if the selection text exists.
Call the command from Karabiner from the above autogen, you can copy text in suitable situation even if you call the command for each button release.
https://pqrs.org/osx/karabiner/xml.html.en#vkopenurldef
