### ISSUE TITLE
Double key down event on every key press

### ISSUE THREAD

**Issue by mirrec** [tekezo/Karabiner#629]
Hey,

first of all, thank you for awesome software.

To my problem. After updating Karabiner to 10.18. and security update on Mac OS X I have found very nasty bug. Every time I press come key on keyboard it fires key down event twice. Basically you cannot use it because you cannot type normally. I couldn't even came back from lock screen because I wasn't able to type in my password (everything was written twice). When I quit karabinier, everything works fine.

I am attaching event log. Any ideas?

![karabinier_event_log](https://cloud.githubusercontent.com/assets/544111/15094954/381859dc-14b4-11e6-8e9a-afcd0e9265c7.png)

* OS X version: 10.9.5
* Karabiner version: 10.18.30
* Your Mac hardware: Macbook Pro 13-inch, Early 2011
* Your keyboard hardware: Keyboard on Macbook

Thanks a lot.

**Comment by ethus3h** [comment]
Possibly this is caused by the change in 10.15.0:

"Please increase the key repeat values to 200 ms and 5 ms from Preferences:
https://pqrs.org/osx/karabiner/document.html.en#keyrepeat

You have set very small key repeat rate in the previous version.
The safety limit of key repeat rate has been removed at Karabiner-10.15.0.
Then, you can overwrite key repeat rate by extreme fast values." —https://github.com/tekezo/Karabiner/issues/553#issuecomment-170764077

Could you check this?

**Comment by mirrec** [comment]
@ethus3h This solved the problem. So I am closing this ticket. Thanks a lot!
