### ISSUE TITLE
Switching Command+Tab to Option+Tab doesn't work

### ISSUE THREAD

**Issue by naveenOnarayanan** [tekezo/Karabiner#748]
After toggling option to make Option+Tab --> Switch Applications, I keep getting 

lock: command
Command + Tab

Im on El Capitan - OS 10.11.6

<img width="354" alt="screen shot 2016-10-14 at 1 13 35 am" src="https://cloud.githubusercontent.com/assets/3528131/19380286/77c75e2e-91ab-11e6-9d8d-f81168b2af7e.png">

**Comment by felipebueno** [comment]
Same here. It stopped working months ago.

I tried to fix it but eventually gave up and tried to get used to using [THEREALOPTIONKEY] + [TAB] to switch applications. But it's still really annoying.

I've found your issue today while trying yet again to fix it 😄

**Comment by tekezo** [comment]
I cannot reproduce this issue.
What settings do you enabled in Karabiner Preferences?

**Comment by felipebueno** [comment]
Hello, @tekezo 

To make sure it wasn't any of my custom settings on private.xml, I disabled everything and enabled just the three settings that wold swap COMMAND_L <-> OPTION_L and enable Option + Tab to Switch Application. I also quit Seil... just in case.

Here's a screenshot:
![karabiner](https://cloud.githubusercontent.com/assets/241271/19838920/08044ada-9ec0-11e6-9c42-67219e8e6213.jpg)

The first line on the EventViewer shows what happens when I press the "real" Switch Application keychord COMMAND_L + TAB. The result is a clean switch app. It works ok.

The next four lines happen when I hit the custom combination enabled by Karabiner. The result is it ignores the pressed OPTION_L (swapped with COMMAND_L) and just do the tab.

Please, let me know if you need any more information.

**Comment by felipebueno** [comment]
Oh, one more thing I forgot to mention. If I just enable the "Use Option + Tab as "switch app" without swapping OPTION_L with COMMAND_L it works. Pressing OPTION_R + TAB also works. The problem seems to happen only when the option key is in the command key's place.

**Comment by tekezo** [comment]
These settings are conflicted.
Could you change the command and option key in other way (Seil or System Preferences)?

**Comment by felipebueno** [comment]
Oh, man, I'm so stupid... I could've done this months ago... I said it stopped working months ago but it wasn't Karabiners fault in the first place... I aways use Seil to swap keys but I, as I only do this one time every N years or so, I forgot to turn it on. I aways think of Seil as the app to make caps-lock useful 😄 

Thanks for the heads up.

**Comment by felipebueno** [comment]
I so happy that my keyboard is working properly now hahah
