### ISSUE TITLE
separate preferences file

### ISSUE THREAD

**Issue by franciscolourenco** [tekezo/Karabiner#9]
It would be really cool to have an external configuration file with a list of all the checked options.

Purpose:
- sync settings between machines (with dropbox, sugarsync, etc..)
- backup and share configs (on github for example)

**Comment by dvcrn** [comment]
Any updates on this? I am also looking for a way to specify either the folder of the plist file or symlink it into my dropbox

**Comment by tekezo** [comment]
There is no progress.
(And I'm working on Sierra support, so I cannot take a time for this issue for a while.)

**Comment by asmeurer** [comment]
For those who want to sync Karabiner preferences with git (it should also work with Dropbox), I wrote a tool that can help: https://github.com/asmeurer/prefsync. I personally use it to sync my [Karabiner prefs](https://github.com/asmeurer/dotfiles/blob/master/Library/Preferences/org.pqrs.Karabiner.plist). For many things that I've tried it with it's a bit annoying to track their preferences in git because they are constantly writing things like timestamps to the pref file, but for Karabiner it works quite nicely (the pref file generally updates only when a pref is changed, or sometimes when Karabiner is updated). To use it run 

```
prefsync ~/Library/Preferences/org.pqrs.Karabiner.plist /path/to/synced/org.pqrs.Karabiner.plist
```

**Comment by aristidesfl** [comment]
Just to confirm, has anyone been able to use Mackup to sync the selected checkboxes?

**Comment by aristidesfl** [comment]
https://github.com/lra/mackup/issues/857

**Comment by aristidesfl** [comment]
I'm using mackup to sync preferences via Dropbox. The problem is that Karabiner is updating `~/Library/Preferences/org.pqrs.Karabiner.plist` as it is being used and causing dropbox to work all the time. Why is Karabiner saving the state to the preferences file instead of keeping it only in memory?
